[env]
PORT = "8000"

[config]
skip_core_tasks = true

# ---- BASIC ----

[tasks.serve]
description = "Start server"
dependencies = ["install-trunk", "install-wasm-bindgen-cli"]
command = "trunk"
args = ["serve", "--port", "${PORT}"]

[tasks.verify]
description = "Format, lint with Clippy and run tests"
dependencies = ["fmt", "clippy"]

# ---- BUILD ----

[tasks.build]
description = "Build with trunk"
dependencies = ["install-trunk", "install-wasm-bindgen-cli"]
command = "trunk"
args = ["build"]

[tasks.build_release]
description = "Build with trunk in release mode"
dependencies = ["install-trunk", "install-wasm-bindgen-cli"]
command = "trunk"
args = ["build", "--release"]

# ---- INSTALL ----

[tasks.install-trunk]
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "-V"}

[tasks.install-wasm-bindgen-cli]
install_crate = { crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg = "--help"}

# ---- LINT ----

[tasks.clippy]
description = "Lint with Clippy"
install_crate = { rustup_component_name = "clippy", binary = "cargo-clippy", test_arg = "--help" }
command = "cargo"
args = ["clippy", "--all-features", "--", "--deny", "warnings", "--deny", "clippy::pedantic", "--deny", "clippy::nursery"]

[tasks.fmt]
description = "Format with rustfmt"
install_crate = { rustup_component_name = "rustfmt", binary = "rustfmt", test_arg = "-V" }
command = "cargo"
args = ["fmt"]